/**
 * USCIS Civics Test — 2020 version (100 questions).
 * Applies to Form N-400 filed before October 20, 2025 (subject to USCIS transition rules).
 * Source: USCIS "100 Civics Questions and Answers" (M-1758), uscis.gov/citizenship.
 * `dynamic: true` marks questions whose correct answer depends on who currently
 * holds an office, or on the applicant's state of residence — see README for how
 * to keep those current.
 */
window.CIVICS_2020 = {
  version: "2020",
  label: "2020 Civics Test",
  totalQuestions: 100,
  passingScore: 6,
  testQuestionCount: 10,
  officialUrl: "https://www.uscis.gov/citizenship/find-study-materials-and-resources/study-for-the-test",
  questions: [
    { id: 1, category: "Principles of American Democracy", question: "What is the supreme law of the land?", answers: ["the Constitution"] },
    { id: 2, category: "Principles of American Democracy", question: "What does the Constitution do?", answers: ["sets up the government", "defines the government", "protects basic rights of Americans"] },
    { id: 3, category: "Principles of American Democracy", question: "The idea of self-government is in the first three words of the Constitution. What are these words?", answers: ["We the People"] },
    { id: 4, category: "Principles of American Democracy", question: "What is an amendment?", answers: ["a change (to the Constitution)", "an addition (to the Constitution)"] },
    { id: 5, category: "Principles of American Democracy", question: "What do we call the first ten amendments to the Constitution?", answers: ["the Bill of Rights"] },
    { id: 6, category: "Principles of American Democracy", question: "What is one right or freedom from the First Amendment?", answers: ["speech", "religion", "assembly", "press", "petition the government"] },
    { id: 7, category: "Principles of American Democracy", question: "How many amendments does the Constitution have?", answers: ["twenty-seven (27)"] },
    { id: 8, category: "Principles of American Democracy", question: "What did the Declaration of Independence do?", answers: ["announced our independence (from Great Britain)", "declared our independence (from Great Britain)", "said that the United States is free (from Great Britain)"] },
    { id: 9, category: "Principles of American Democracy", question: "What are two rights in the Declaration of Independence?", answers: ["life", "liberty", "pursuit of happiness"] },
    { id: 10, category: "Principles of American Democracy", question: "What is freedom of religion?", answers: ["You can practice any religion, or not practice a religion."] },
    { id: 11, category: "Principles of American Democracy", question: "What is the economic system in the United States?", answers: ["capitalist economy", "market economy"] },
    { id: 12, category: "Principles of American Democracy", question: "What is the “rule of law”?", answers: ["Everyone must follow the law.", "Leaders must obey the law.", "Government must obey the law.", "No one is above the law."] },

    { id: 13, category: "System of Government", question: "Name one branch or part of the government.", answers: ["Congress", "legislative", "President", "executive", "the courts", "judicial"] },
    { id: 14, category: "System of Government", question: "What stops one branch of government from becoming too powerful?", answers: ["checks and balances", "separation of powers"] },
    { id: 15, category: "System of Government", question: "Who is in charge of the executive branch?", answers: ["the President"] },
    { id: 16, category: "System of Government", question: "Who makes federal laws?", answers: ["Congress", "Senate and House (of Representatives)", "(U.S. or national) legislature"] },
    { id: 17, category: "System of Government", question: "What are the two parts of the U.S. Congress?", answers: ["the Senate and House (of Representatives)"] },
    { id: 18, category: "System of Government", question: "How many U.S. Senators are there?", answers: ["one hundred (100)"] },
    { id: 19, category: "System of Government", question: "We elect a U.S. Senator for how many years?", answers: ["six (6)"] },
    { id: 20, category: "System of Government", question: "Who is one of your state’s U.S. Senators now?", answers: ["Answers will vary by state."], dynamic: true, dynamicNote: "Depends on the applicant's state of residence. Look up current senators at senate.gov." },
    { id: 21, category: "System of Government", question: "The House of Representatives has how many voting members?", answers: ["four hundred thirty-five (435)"] },
    { id: 22, category: "System of Government", question: "We elect a U.S. Representative for how many years?", answers: ["two (2)"] },
    { id: 23, category: "System of Government", question: "Name your U.S. Representative.", answers: ["Answers will vary by district."], dynamic: true, dynamicNote: "Depends on the applicant's congressional district. Look up your representative at house.gov." },
    { id: 24, category: "System of Government", question: "Who does a U.S. Senator represent?", answers: ["all people of the state"] },
    { id: 25, category: "System of Government", question: "Why do some states have more Representatives than other states?", answers: ["because of the state’s population", "they have more people", "some states have more people"] },
    { id: 26, category: "System of Government", question: "We elect a President for how many years?", answers: ["four (4)"] },
    { id: 27, category: "System of Government", question: "In what month do we vote for President?", answers: ["November"] },
    { id: 28, category: "System of Government", question: "What is the name of the President of the United States now?", answers: [], dynamic: true, dynamicNote: "Visit uscis.gov/citizenship/testupdates for the current President." },
    { id: 29, category: "System of Government", question: "What is the name of the Vice President of the United States now?", answers: [], dynamic: true, dynamicNote: "Visit uscis.gov/citizenship/testupdates for the current Vice President." },
    { id: 30, category: "System of Government", question: "If the President can no longer serve, who becomes President?", answers: ["the Vice President"] },
    { id: 31, category: "System of Government", question: "If both the President and the Vice President can no longer serve, who becomes President?", answers: ["the Speaker of the House"] },
    { id: 32, category: "System of Government", question: "Who is the Commander in Chief of the military?", answers: ["the President"] },
    { id: 33, category: "System of Government", question: "Who signs bills to become laws?", answers: ["the President"] },
    { id: 34, category: "System of Government", question: "Who vetoes bills?", answers: ["the President"] },
    { id: 35, category: "System of Government", question: "What does the President’s Cabinet do?", answers: ["advises the President"] },
    { id: 36, category: "System of Government", question: "What are two Cabinet-level positions?", answers: ["Secretary of Agriculture", "Secretary of Commerce", "Secretary of Defense", "Secretary of Education", "Secretary of Energy", "Secretary of Health and Human Services", "Secretary of Homeland Security", "Secretary of Housing and Urban Development", "Secretary of the Interior", "Secretary of Labor", "Secretary of State", "Secretary of Transportation", "Secretary of the Treasury", "Secretary of Veterans Affairs", "Attorney General", "Vice President"] },
    { id: 37, category: "System of Government", question: "What does the judicial branch do?", answers: ["reviews laws", "explains laws", "resolves disputes (disagreements)", "decides if a law goes against the Constitution"] },
    { id: 38, category: "System of Government", question: "What is the highest court in the United States?", answers: ["the Supreme Court"] },
    { id: 39, category: "System of Government", question: "How many justices are on the Supreme Court?", answers: [], dynamic: true, dynamicNote: "Visit uscis.gov/citizenship/testupdates for the current number of justices." },
    { id: 40, category: "System of Government", question: "Who is the Chief Justice of the United States now?", answers: [], dynamic: true, dynamicNote: "Visit uscis.gov/citizenship/testupdates for the current Chief Justice." },
    { id: 41, category: "System of Government", question: "Under our Constitution, some powers belong to the federal government. What is one power of the federal government?", answers: ["to print money", "to declare war", "to create an army", "to make treaties"] },
    { id: 42, category: "System of Government", question: "Under our Constitution, some powers belong to the states. What is one power of the states?", answers: ["provide schooling and education", "provide protection (police)", "provide safety (fire departments)", "give a driver’s license", "approve zoning and land use"] },
    { id: 43, category: "System of Government", question: "Who is the Governor of your state now?", answers: ["Answers will vary by state."], dynamic: true, dynamicNote: "Depends on the applicant's state of residence." },
    { id: 44, category: "System of Government", question: "What is the capital of your state?", answers: ["Answers will vary by state."], dynamic: true, dynamicNote: "Depends on the applicant's state of residence." },
    { id: 45, category: "System of Government", question: "What are the two major political parties in the United States?", answers: ["Democratic and Republican"] },
    { id: 46, category: "System of Government", question: "What is the political party of the President now?", answers: [], dynamic: true, dynamicNote: "Visit uscis.gov/citizenship/testupdates for the President's current political party." },
    { id: 47, category: "System of Government", question: "What is the name of the Speaker of the House of Representatives now?", answers: [], dynamic: true, dynamicNote: "Visit uscis.gov/citizenship/testupdates for the current Speaker of the House." },

    { id: 48, category: "Rights and Responsibilities", question: "There are four amendments to the Constitution about who can vote. Describe one of them.", answers: ["Citizens eighteen (18) and older (can vote).", "You don’t have to pay (a poll tax) to vote.", "Any citizen can vote. (Women and men can vote.)", "A male citizen of any race (can vote.)"] },
    { id: 49, category: "Rights and Responsibilities", question: "What is one responsibility that is only for United States citizens?", answers: ["serve on a jury", "vote in a federal election"] },
    { id: 50, category: "Rights and Responsibilities", question: "Name one right only for United States citizens.", answers: ["vote in a federal election", "run for federal office"] },
    { id: 51, category: "Rights and Responsibilities", question: "What are two rights of everyone living in the United States?", answers: ["freedom of expression", "freedom of speech", "freedom of assembly", "freedom to petition the government", "freedom of religion", "the right to bear arms"] },
    { id: 52, category: "Rights and Responsibilities", question: "What do we show loyalty to when we say the Pledge of Allegiance?", answers: ["the United States", "the flag"] },
    { id: 53, category: "Rights and Responsibilities", question: "What is one promise you make when you become a United States citizen?", answers: ["give up loyalty to other countries", "defend the Constitution and laws of the United States", "obey the laws of the United States", "serve in the U.S. military (if needed)", "serve (do important work for) the nation (if needed)", "be loyal to the United States"] },
    { id: 54, category: "Rights and Responsibilities", question: "How old do citizens have to be to vote for President?", answers: ["eighteen (18) and older"] },
    { id: 55, category: "Rights and Responsibilities", question: "What are two ways that Americans can participate in their democracy?", answers: ["vote", "join a political party", "help with a campaign", "join a civic group", "join a community group", "give an elected official your opinion on an issue", "call Senators and Representatives", "publicly support or oppose an issue or policy", "run for office", "write to a newspaper"] },
    { id: 56, category: "Rights and Responsibilities", question: "When is the last day you can send in federal income tax forms?", answers: ["April 15"] },
    { id: 57, category: "Rights and Responsibilities", question: "When must all men register for the Selective Service?", answers: ["at age eighteen (18)", "between eighteen (18) and twenty-six (26)"] },

    { id: 58, category: "Colonial Period and Independence", question: "What is one reason colonists came to America?", answers: ["freedom", "political liberty", "religious freedom", "economic opportunity", "practice their religion", "escape persecution"] },
    { id: 59, category: "Colonial Period and Independence", question: "Who lived in America before the Europeans arrived?", answers: ["American Indians", "Native Americans"] },
    { id: 60, category: "Colonial Period and Independence", question: "What group of people was taken to America and sold as slaves?", answers: ["Africans", "people from Africa"] },
    { id: 61, category: "Colonial Period and Independence", question: "Why did the colonists fight the British?", answers: ["because of high taxes (taxation without representation)", "because the British army stayed in their houses (boarding, quartering)", "because they didn’t have self-government"] },
    { id: 62, category: "The Founding Fathers", question: "Who wrote the Declaration of Independence?", answers: ["(Thomas) Jefferson"] },
    { id: 63, category: "Colonial Period and Independence", question: "When was the Declaration of Independence adopted?", answers: ["July 4, 1776"] },
    { id: 64, category: "Colonial Period and Independence", question: "There were 13 original states. Name three.", answers: ["New Hampshire", "Massachusetts", "Rhode Island", "Connecticut", "New York", "New Jersey", "Pennsylvania", "Delaware", "Maryland", "Virginia", "North Carolina", "South Carolina", "Georgia"] },
    { id: 65, category: "Colonial Period and Independence", question: "What happened at the Constitutional Convention?", answers: ["The Constitution was written.", "The Founding Fathers wrote the Constitution."] },
    { id: 66, category: "Colonial Period and Independence", question: "When was the Constitution written?", answers: ["1787"] },
    { id: 67, category: "The Founding Fathers", question: "The Federalist Papers supported the passage of the U.S. Constitution. Name one of the writers.", answers: ["(James) Madison", "(Alexander) Hamilton", "(John) Jay", "Publius"] },
    { id: 68, category: "The Founding Fathers", question: "What is one thing Benjamin Franklin is famous for?", answers: ["U.S. diplomat", "oldest member of the Constitutional Convention", "first Postmaster General of the United States", "writer of ‘Poor Richard’s Almanac’", "started the first free libraries"] },
    { id: 69, category: "The Founding Fathers", question: "Who is the ‘Father of Our Country’?", answers: ["(George) Washington"] },
    { id: 70, category: "The Founding Fathers", question: "Who was the first President?", answers: ["(George) Washington"] },

    { id: 71, category: "1800s", question: "What territory did the United States buy from France in 1803?", answers: ["the Louisiana Territory", "Louisiana"] },
    { id: 72, category: "1800s", question: "Name one war fought by the United States in the 1800s.", answers: ["War of 1812", "Mexican-American War", "Civil War", "Spanish-American War"] },
    { id: 73, category: "1800s", question: "Name the U.S. war between the North and the South.", answers: ["the Civil War", "the War between the States"] },
    { id: 74, category: "1800s", question: "Name one problem that led to the Civil War.", answers: ["slavery", "economic reasons", "states’ rights"] },
    { id: 75, category: "1800s", question: "What was one important thing that Abraham Lincoln did?", answers: ["freed the slaves (Emancipation Proclamation)", "saved (or preserved) the Union", "led the United States during the Civil War"] },
    { id: 76, category: "1800s", question: "What did the Emancipation Proclamation do?", answers: ["freed the slaves", "freed slaves in the Confederacy", "freed slaves in the Confederate states", "freed slaves in most Southern states"] },
    { id: 77, category: "1800s", question: "What did Susan B. Anthony do?", answers: ["fought for women’s rights", "fought for civil rights"] },

    { id: 78, category: "Recent American History", question: "Name one war fought by the United States in the 1900s.", answers: ["World War I", "World War II", "Korean War", "Vietnam War", "(Persian) Gulf War"] },
    { id: 79, category: "Recent American History", question: "Who was President during World War I?", answers: ["(Woodrow) Wilson"] },
    { id: 80, category: "Recent American History", question: "Who was President during the Great Depression and World War II?", answers: ["(Franklin) Roosevelt"] },
    { id: 81, category: "Recent American History", question: "Who did the United States fight in World War II?", answers: ["Japan, Germany, and Italy"] },
    { id: 82, category: "Recent American History", question: "Before he was President, Eisenhower was a general. What war was he in?", answers: ["World War II"] },
    { id: 83, category: "Recent American History", question: "During the Cold War, what was the main concern of the United States?", answers: ["Communism"] },
    { id: 84, category: "Recent American History", question: "What movement tried to end racial discrimination?", answers: ["civil rights (movement)"] },
    { id: 85, category: "Recent American History", question: "What did Martin Luther King, Jr. do?", answers: ["fought for civil rights", "worked for equality for all Americans"] },
    { id: 86, category: "Recent American History", question: "What major event happened on September 11, 2001, in the United States?", answers: ["Terrorists attacked the United States."] },

    { id: 87, category: "Geography", question: "Name one American Indian tribe in the United States.", answers: ["Cherokee", "Navajo", "Sioux", "Chippewa", "Choctaw", "Pueblo", "Apache", "Iroquois", "Creek", "Blackfeet", "Seminole", "Cheyenne", "Arawak", "Shawnee", "Mohegan", "Huron", "Oneida", "Lakota", "Crow", "Teton", "Hopi", "Inuit"] },
    { id: 88, category: "Geography", question: "Name one of the two longest rivers in the United States.", answers: ["Missouri (River)", "Mississippi (River)"] },
    { id: 89, category: "Geography", question: "What ocean is on the West Coast of the United States?", answers: ["Pacific (Ocean)"] },
    { id: 90, category: "Geography", question: "What ocean is on the East Coast of the United States?", answers: ["Atlantic (Ocean)"] },
    { id: 91, category: "Geography", question: "Name one U.S. territory.", answers: ["Puerto Rico", "U.S. Virgin Islands", "American Samoa", "Northern Mariana Islands", "Guam"] },
    { id: 92, category: "Geography", question: "Name one state that borders Canada.", answers: ["Maine", "New Hampshire", "Vermont", "New York", "Pennsylvania", "Ohio", "Michigan", "Minnesota", "North Dakota", "Montana", "Idaho", "Washington", "Alaska"] },
    { id: 93, category: "Geography", question: "Name one state that borders Mexico.", answers: ["California", "Arizona", "New Mexico", "Texas"] },
    { id: 94, category: "Geography", question: "What is the capital of the United States?", answers: ["Washington, D.C."] },
    { id: 95, category: "Geography", question: "Where is the Statue of Liberty?", answers: ["New York (Harbor)", "Liberty Island"] },

    { id: 96, category: "Symbols", question: "Why does the flag have 13 stripes?", answers: ["because there were 13 original colonies", "because the stripes represent the original colonies"] },
    { id: 97, category: "Symbols", question: "Why does the flag have 50 stars?", answers: ["because there is one star for each state", "because each star represents a state", "because there are 50 states"] },
    { id: 98, category: "Symbols", question: "What is the name of the national anthem?", answers: ["The Star-Spangled Banner"] },

    { id: 99, category: "Holidays", question: "When do we celebrate Independence Day?", answers: ["July 4"] },
    { id: 100, category: "Holidays", question: "Name two national U.S. holidays.", answers: ["New Year’s Day", "Martin Luther King, Jr. Day", "Presidents’ Day", "Memorial Day", "Independence Day", "Labor Day", "Columbus Day", "Veterans Day", "Thanksgiving", "Christmas"] }
  ]
};
